param(
    [string]$ContainerName = "oracle-vector-db",
    [string]$OraclePassword = "ParolaProiect123#",
    [string]$ServiceName = "FREEPDB1",
    [string]$AppUser = "proiect_ai",
    [string]$AppPassword = "proiect_ai"
)

$ErrorActionPreference = "Stop"

function Invoke-SqlPlus {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Sql
    )

    $connection = "sys/$OraclePassword@$ServiceName as sysdba"
    $Sql | docker exec -i $ContainerName sqlplus -L -S $connection
}

Write-Host "Checking Docker container '$ContainerName'..."
$containerStatus = docker inspect -f "{{.State.Status}} {{.State.Health.Status}}" $ContainerName 2>$null
if ($LASTEXITCODE -ne 0) {
    throw "Container '$ContainerName' was not found. Start it with docker run first."
}

if ($containerStatus -notmatch "^running") {
    throw "Container '$ContainerName' is not running. Current status: $containerStatus"
}

Write-Host "Waiting for Oracle service '$ServiceName' to accept connections..."
$ready = $false
for ($attempt = 1; $attempt -le 30; $attempt++) {
    $probe = @"
SET HEADING OFF FEEDBACK OFF PAGESIZE 0 VERIFY OFF ECHO OFF
SELECT 'READY' FROM dual;
EXIT;
"@

    $output = Invoke-SqlPlus -Sql $probe 2>&1
    if ($LASTEXITCODE -eq 0 -and ($output -join "`n") -match "READY") {
        $ready = $true
        break
    }

    Start-Sleep -Seconds 5
}

if (-not $ready) {
    throw "Oracle service '$ServiceName' did not become ready in time."
}

Write-Host "Initializing application user and vector schema..."
$sql = @"
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON
SET DEFINE OFF

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM dba_users
    WHERE username = UPPER('$AppUser');

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER $AppUser IDENTIFIED BY "$AppPassword"';
        DBMS_OUTPUT.PUT_LINE('Created user $AppUser.');
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER $AppUser IDENTIFIED BY "$AppPassword" ACCOUNT UNLOCK';
        DBMS_OUTPUT.PUT_LINE('User $AppUser already exists; password reset and account unlocked.');
    END IF;
END;
/

GRANT CREATE SESSION TO $AppUser;
GRANT CREATE TABLE TO $AppUser;
GRANT CREATE SEQUENCE TO $AppUser;
GRANT CREATE VIEW TO $AppUser;
GRANT UNLIMITED TABLESPACE TO $AppUser;
ALTER USER $AppUser DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE $AppUser.document_chunks PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE $AppUser.documents PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE $AppUser.documente PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE $AppUser.documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR2(300) NOT NULL,
    source_type VARCHAR2(30) DEFAULT 'manual' NOT NULL,
    uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    pdf_title VARCHAR2(500),
    pdf_author VARCHAR2(300),
    file_size_bytes NUMBER,
    CONSTRAINT chk_documents_source_type
        CHECK (source_type IN ('pdf', 'txt', 'md', 'manual'))
);

CREATE TABLE $AppUser.document_chunks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id NUMBER NOT NULL,
    chunk_index NUMBER NOT NULL,
    page_number NUMBER,
    content CLOB NOT NULL,
    embedding VECTOR(384, FLOAT32),
    CONSTRAINT fk_document_chunks_document
        FOREIGN KEY (document_id)
        REFERENCES $AppUser.documents(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_document_chunk_index UNIQUE (document_id, chunk_index)
);

CREATE INDEX $AppUser.idx_document_chunks_doc_id
    ON $AppUser.document_chunks(document_id);

CREATE INDEX $AppUser.idx_documents_uploaded_at
    ON $AppUser.documents(uploaded_at);

COMMIT;

PROMPT
PROMPT Initialization summary:
SELECT COUNT(*) AS documents FROM $AppUser.documents;
SELECT COUNT(*) AS chunks FROM $AppUser.document_chunks;
SELECT username, account_status FROM dba_users WHERE username = UPPER('$AppUser');

PROMPT
PROMPT JDBC settings:
PROMPT spring.datasource.url=jdbc:oracle:thin:@localhost:1521/$ServiceName
PROMPT spring.datasource.username=$AppUser
PROMPT spring.datasource.password=$AppPassword

EXIT;
"@

$result = Invoke-SqlPlus -Sql $sql 2>&1
$exitCode = $LASTEXITCODE
$result | Write-Host

if ($exitCode -ne 0) {
    throw "Database initialization failed with exit code $exitCode."
}

Write-Host "Database initialization completed successfully."
